"""added jira_id column to tasks table

Revision ID: bffe2447f994
Revises: 245358b60f38
Create Date: 2023-08-23 07:38:28.371882+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffe2447f994'
down_revision = '245358b60f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('jira_id', sa.String(length=320), nullable=True), schema='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'jira_id', schema='tasks')
    # ### end Alembic commands ###
